name: CI pour Appli Python

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python Libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Create Bundle Zip
      run: |
       
        # Exemple : zip -r my_bundle.zip .

    - name: Upload Bundle Zip
      uses: actions/upload-artifact@v2
      with:
        name: my_bundle  
        path: my_bundle.zip  
