name: CI pour Appli Python

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python Libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assurez-vous d'ajuster cela selon le nom de votre fichier requirements.txt

    - name: Create Bundle Zip
      run: |
        # Ajoutez ici les commandes nécessaires pour créer votre bundle Zip
        # Exemple : zip -r my_bundle.zip .

    - name: Upload Bundle Zip
      uses: actions/upload-artifact@v2
      with:
        name: my_bundle  # Nom de votre bundle, à ajuster selon vos besoins
        path: my_bundle.zip  # Chemin vers votre bundle, à ajuster selon vos besoins
